combine_control_expr = false
condense_wildcard_suffixes = true
edition = "2021"
error_on_line_overflow = true
error_on_unformatted = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
style_edition = "2021"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
